"""update comment table

Revision ID: 8b976517bfcc
Revises: 38fce3be0233
Create Date: 2019-03-02 16:18:02.884731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b976517bfcc'
down_revision = '38fce3be0233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
