"""update table post

Revision ID: be5973141abd
Revises: bec6814f6820
Create Date: 2019-03-02 11:58:54.170485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5973141abd'
down_revision = 'bec6814f6820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
